---
functional:
  - Требование 1 Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Требование 2 Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Требование 3 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Требование 4 Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
implicit:
  - Требование 5 Изменять описание товара.
  - Требование 6 Должна быть возможность отмены заказа
