---
functional:
  -  Пользователь будет просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
  -  На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее.
  -  Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге.
  -  На странице корзины пользователь сможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  -  Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  -  Пользователь должен иметь возможность фильтровать товары.
  -  Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  -  Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  -  Сайт должен иметь мобильную версию.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Требование 5 Изменять описание товара.
  - Требование 6 Должна быть возможность отмены заказа
